/* Local-only real Paper fixture. It never connects to a live server. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process'),{DatabaseSync}=require('node:sqlite'),mc=require('minecraft-protocol'),nbt=require('prismarine-nbt'),data=require('minecraft-data')('1.21.11');
const repo=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(process.env.MK_SMOKE_PARENT||os.tmpdir(),'mk-market-smoke-'));
const port=Number(process.env.MK_MARKET_PORT||25588),version='1.6.0';
assert(process.env.PAPER_JAR&&fs.existsSync(process.env.PAPER_JAR),'Set PAPER_JAR; running this isolated fixture accepts the Minecraft EULA.');
fs.mkdirSync(path.join(dir,'plugins/MKSidebarRanks'),{recursive:true});fs.copyFileSync(process.env.PAPER_JAR,path.join(dir,'paper.jar'));
fs.copyFileSync(path.join(repo,`target/mk-sidebar-ranks-${version}.jar`),path.join(dir,'plugins/mk-sidebar-ranks.jar'));
for(const name of ['libraries','versions','cache']){const source=path.join(process.env.MK_LOAD_CACHE||path.join(repo,'../../work/smoke-server'),name);if(fs.existsSync(source))fs.cpSync(source,path.join(dir,name),{recursive:true});}
const cfg=path.join(dir,'plugins/MKSidebarRanks/config.yml'),database=path.join(dir,'plugins/MKSidebarRanks/market.db');
let config=fs.readFileSync(path.join(repo,'src/main/resources/config.yml'),'utf8').replace('interval-seconds: 120','interval-seconds: 30').replace('refresh-seconds: 60','refresh-seconds: 10').replace('waiting-seconds: 300','waiting-seconds: 10');fs.writeFileSync(cfg,config);
fs.writeFileSync(path.join(dir,'eula.txt'),'eula=true\n');fs.writeFileSync(path.join(dir,'server.properties'),`server-ip=127.0.0.1\nserver-port=${port}\nonline-mode=false\nenforce-secure-profile=false\nspawn-protection=0\ngamemode=survival\ndifficulty=peaceful\nview-distance=2\nsimulation-distance=2\nlevel-type=minecraft:flat\ngenerate-structures=false\npause-when-empty-seconds=-1\n`);
let child,log='',clients=[],sql;const results=[],samples=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const uuid=name=>{let b=crypto.createHash('md5').update('OfflinePlayer:'+name).digest();b[6]=(b[6]&15)|48;b[8]=(b[8]&63)|128;const h=b.toString('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};
const plain=raw=>{if(raw==null)return '';if(raw && raw.type){try{raw=nbt.simplify(raw);}catch{}}if(raw==null)return "";if(typeof raw==='string')return raw;if(Array.isArray(raw))return raw.map(plain).join('');return (raw.text||raw['']||raw.translate||'')+plain(raw.extra||[]);};
const flipSoundNames=['block.note_block.hat','block.note_block.bass','entity.player.levelup'],flipSoundIds=flipSoundNames.map(name=>data.soundsByName[name].id-1);
async function wait(check,label,timeout=20000){const start=Date.now();while(!check()){if(Date.now()-start>timeout)throw Error('Timeout '+label+'\n'+log.slice(-2500));await sleep(75);}}
function pass(label){results.push(label);console.log('PASS:',label);}
function cmd(line){child.stdin.write(line+'\n');}
function chat(p,line){p.client.write('chat_command',{command:line});}
function query(q,...args){return sql.prepare(q).all(...args);}
function balance(p){return Number(query('SELECT cents FROM wallets WHERE uuid=?',uuid(p.name))[0]?.cents);}
function listing(){return query("SELECT * FROM listings WHERE state='ACTIVE' ORDER BY id DESC")[0];}
async function boot(){log='';child=spawn('java',['-Xms512M','-Xmx1536M','-jar','paper.jar','--nogui'],{cwd:dir,stdio:['pipe','pipe','pipe'],windowsHide:true});child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);await wait(()=>log.includes('Done ('),'startup',180000);assert(log.includes('MK Sidebar & Ranks enabled'));sql=new DatabaseSync(database);sql.exec('PRAGMA busy_timeout=5000');console.log('Market fixture:',dir);}
async function stop(){clients.forEach(p=>p.client.end());clients=[];if(child&&child.exitCode===null){cmd('stop');await wait(()=>child.exitCode!==null,'shutdown',60000);}if(sql){sql.close();sql=null;}fs.appendFileSync(path.join(dir,'server.log'),log);}
async function connect(name){
 const p={name,messages:[],windows:[],inventory:[],lines:new Map(),spawns:[],metadata:[],frames:new Set(),sounds:0,client:mc.createClient({host:'127.0.0.1',port,username:name,auth:'offline',version:'1.21.11'})};clients.push(p);
 p.client.on('sound_effect',q=>{if(flipSoundIds.includes(q.sound?.soundId)||flipSoundNames.some(name=>JSON.stringify(q.sound).includes(name)))p.sounds++;});
 p.client.on('error',e=>p.error=e);p.client.on('system_chat',q=>p.messages.push(plain(q.content)));p.client.on('position',q=>{p.position=q;p.client.write('teleport_confirm',{teleportId:q.teleportId});});
 p.client.on('scoreboard_score',q=>p.lines.set(q.itemName,plain(q.display_name)));p.client.on('open_window',q=>{p.window={id:q.windowId,title:plain(q.windowTitle),items:[],state:0};p.windows.push(p.window);});
 p.client.on('window_items',q=>{if(q.windowId===0)p.inventory=q.items;if(p.window?.id===q.windowId){p.window.items=q.items;p.window.state=q.stateId;}});
 p.client.on('set_slot',q=>{if(q.windowId===0)p.inventory[q.slot]=q.item;if(p.window?.id===q.windowId){p.window.items[q.slot]=q.item;p.window.state=q.stateId;if(p.window.title.includes('MK COIN FLIP #')&&q.slot===13)p.frames.add(q.item?.itemId);}});
 p.client.on('set_player_inventory',q=>{p.inventory[q.slotId]=q.contents;});p.client.on('close_window',q=>{if(p.window?.id===q.windowId)p.window=null;});
 p.client.on('spawn_entity',q=>p.spawns.push(q));p.client.on('entity_metadata',q=>p.metadata.push(q));
 await wait(()=>p.lines.size>=10||p.error,name+' joined');if(p.error)throw p.error;await sleep(250);return p;
}
async function message(p,line,expected){await sleep(350);const offset=p.messages.length;chat(p,line);await wait(()=>p.messages.slice(offset).some(m=>m.includes(expected)),line+' response');return p.messages.slice(offset);}
async function open(p,line,title){await sleep(350);chat(p,line);await wait(()=>p.window?.title.includes(title)&&p.window.items.length>0,line+' menu');await sleep(350);return p.window;}
async function click(p,slot,mode=0){p.client.write('window_click',{windowId:p.window.id,stateId:p.window.state,slot,mouseButton:0,mode,changedSlots:[],cursorItem:undefined});await sleep(450);}
function closeWindow(p){if(p.window){p.client.write('close_window',{windowId:p.window.id});p.window=null;}}
async function sell(p,item,amount,price){closeWindow(p);cmd(`item replace entity ${p.name} hotbar.0 with minecraft:${item} ${amount}`);await sleep(350);const offset=p.messages.length;chat(p,`auction sell ${price}`);await wait(()=>p.messages.slice(offset).some(m=>m.includes('Listed ')),'list item');return listing();}
async function claim(p){await open(p,'auction mail','MK MAILBOX');const offset=p.messages.length;await click(p,0);await wait(()=>p.messages.slice(offset).some(m=>m.includes('Item claimed')),'claim item');}
async function screenshotData(label,p){samples.push({label,window:p.window&&{title:p.window.title,items:p.window.items},messages:p.messages.slice(-8),lines:[...p.lines]});}
(async()=>{try{
 await boot();let alex=await connect('MarketAlex'),sam=await connect('MarketSam'),lee=await connect('MarketLee');
 assert.equal(balance(alex),50000);assert.equal(balance(sam),50000);await message(alex,'money','Balance: $500.00');await wait(()=>[...alex.lines.values()].includes('Money: $500.00'),'money sidebar');pass('New players get $500 once and see it in wallet and compact sidebar');
 await message(alex,'pay MarketSam 25','Sent $25.00');assert.equal(balance(alex),47500);assert.equal(balance(sam),52500);pass('Ordinary players can transfer money and recipients receive confirmation');
 await message(alex,'pay MarketSam 99999','Not enough money');await message(alex,'pay MarketSam -5','Use a positive amount');pass('Invalid and unaffordable transfers cannot change balances');
 chat(alex,'mkmarket money add MarketAlex 999');await sleep(500);assert.equal(balance(alex),47500);cmd('mkmarket money add MarketAlex 25');await wait(()=>balance(alex)===50000,'admin add');cmd('mkmarket money remove MarketSam 25');await wait(()=>balance(sam)===50000,'admin remove');pass('Admin add/remove works from console; ordinary players cannot grant themselves money');
 await message(alex,'baltop','Top balances');assert(alex.messages.some(m=>m.includes('MarketAlex')&&m.includes('$500.00')));pass('Everyone can view the top-money leaderboard');
 const sale=await sell(alex,'diamond',16,125);assert.equal(sale.price,12500);assert.equal(query('SELECT COUNT(*) AS n FROM inventory_ops')[0].n,0);cmd('execute if items entity MarketAlex hotbar.0 minecraft:diamond run say BAD_HELD_DIAMOND');await sleep(250);assert(!log.includes('[Not Secure] BAD_HELD_DIAMOND'));pass('Listing escrows the held stack and persists its fixed total price');
 await open(sam,'auction','MK MARKET');assert.equal(sam.window.items[0].itemId,data.itemsByName.diamond.id);await screenshotData('market',sam);await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM PURCHASE'),'confirmation');await screenshotData('confirmation',sam);assert.equal(balance(sam),50000);await click(sam,15);await wait(()=>sam.window?.title.includes('MK MARKET'),'cancel purchase');assert.equal(balance(sam),50000);pass('Viewing and cancelling a purchase confirmation does not spend money');
 await sleep(350);await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM PURCHASE'),'confirm again');await click(sam,11);await wait(()=>balance(sam)===37500&&balance(alex)===62500,'purchase funds');assert.equal(query("SELECT COUNT(*) AS n FROM mail WHERE owner=? AND state='READY'",uuid(sam.name))[0].n,1);pass('Confirmed purchase pays seller exactly once and puts the exact item in buyer mailbox');
 for(let slot=0;slot<27;slot++)cmd('item replace entity MarketSam inventory.'+slot+' with minecraft:stone 64');for(let slot=0;slot<9;slot++)cmd('item replace entity MarketSam hotbar.'+slot+' with minecraft:stone 64');await sleep(350);
 await open(sam,'auction mail','MK MAILBOX');const fullOffset=sam.messages.length;await click(sam,0);await wait(()=>sam.messages.slice(fullOffset).some(m=>m.includes('Make room')),'full inventory rejection');assert.equal(query("SELECT COUNT(*) AS n FROM mail WHERE owner=? AND state='READY'",uuid(sam.name))[0].n,1);pass('Full inventory cannot consume or partially deliver a mailbox stack');
 closeWindow(sam);cmd('clear MarketSam minecraft:stone');await sleep(350);
 await claim(sam);cmd('execute if items entity MarketSam hotbar.* minecraft:diamond run say RECEIVED_DIAMOND_STACK');await wait(()=>log.includes('RECEIVED_DIAMOND_STACK'),'inventory received');assert.equal(query("SELECT COUNT(*) AS n FROM mail WHERE owner=? AND state='READY'",uuid(sam.name))[0].n,0);assert(sam.inventory.some(i=>i?.itemId===data.itemsByName.diamond.id&&i.itemCount===16));pass('Mailbox delivers the exact purchased stack without leaving a duplicate claim');
 const cancelled=await sell(alex,'oak_log',32,10);await message(alex,`auction cancel ${cancelled.id}`,'Listing cancelled');await claim(alex);pass('Cancelled listings return the complete stack through mailbox');
 const offlineSale=await sell(alex,'iron_ingot',4,20);alex.client.end();await sleep(400);await open(sam,'auction','MK MARKET');await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM PURCHASE'),'offline purchase');await click(sam,11);await wait(()=>balance(sam)===35500,'offline sale');alex=await connect('MarketAlex');assert.equal(balance(alex),64500);pass('Offline sellers receive proceeds without losing their wallet or receiving starter money again');
 await message(alex,'money history','SALE');pass('Transaction history includes sale receipts');
 await open(lee,'auction','MK MARKET');await click(lee,45);await screenshotData('filtered-market',lee);closeWindow(lee);pass('Market category filters and navigation open as native inventory menus');
 closeWindow(sam);await message(alex,'coinflip create 50','Created coin flip #');assert.equal(balance(alex),59500);
 await open(sam,'coinflip','MK COIN FLIPS');assert.equal(sam.window.items[0].itemId,data.itemsByName.player_head.id);await screenshotData('coinflip-lobby',sam);
 await click(sam,0,1);await wait(()=>sam.window?.title.includes('CONFIRM COIN FLIP'),'join confirmation');await screenshotData('coinflip-confirmation',sam);assert.equal(balance(sam),35500);await click(sam,15);await wait(()=>sam.window?.title.includes('MK COIN FLIPS'),'join back');assert(!sam.inventory.some(i=>i?.itemId===data.itemsByName.player_head.id));pass('Public lobby shows waiting heads and stakes; confirmation/back and shift-click cannot take items or charge money');
 await message(alex,'coinflip create 10','already have');await click(alex,0);await wait(()=>alex.messages.some(m=>m.includes('cannot join your own')),'self-join denied');await message(alex,'coinflip cancel','refunded');assert.equal(balance(alex),64500);pass('One waiting wager per player and self-join protection; command cancellation refunds the stake');
 await message(alex,'coinflip create 10','Created coin flip #');await click(alex,50);await wait(()=>balance(alex)===64500,'GUI cancellation');pass('Cancel My Flip button refunds unmatched wagers');
 const before=balance(alex)+balance(sam),leeBefore=balance(lee);await message(alex,'coinflip create 50','Created coin flip #');
 await open(lee,'coinflip','MK COIN FLIPS');await click(lee,0);await wait(()=>lee.window?.title.includes('CONFIRM COIN FLIP'),'stale join view');
 await open(sam,'coinflip','MK COIN FLIPS');await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM COIN FLIP'),'join view');alex.frames.clear();sam.frames.clear();await click(sam,11);
 await wait(()=>alex.window?.title.includes('MK COIN FLIP #')&&sam.window?.title.includes('MK COIN FLIP #'),'both match menus');
 const running=query("SELECT * FROM flips WHERE state='RUNNING' ORDER BY id DESC")[0];assert(running?.winner);assert.equal(balance(alex)+balance(sam),before-10000);pass('Joining saves one 50/50 winner and reserves both stakes; payout does not happen immediately');
 const staleOffset=lee.messages.length;await click(lee,11);await wait(()=>lee.messages.slice(staleOffset).some(m=>m.includes('already started or expired')),'stale join rejection');assert.equal(balance(lee),leeBefore);pass('A stale confirmation cannot start a second match or charge a third player');
 closeWindow(sam);await open(sam,'coinflip','MK COIN FLIP #');assert(sam.window.title.endsWith('#'+running.id));await message(alex,'coinflip cancel','no waiting flip');
 await wait(()=>query('SELECT state FROM flips WHERE id=?',running.id)[0].state==='DONE','animated payout');await wait(()=>sam.messages.some(m=>m.includes(`in coin flip #${running.id}!`)),'result chat');assert.equal(balance(alex)+balance(sam),before);
 assert(alex.frames.has(data.itemsByName.red_stained_glass_pane.id)&&alex.frames.has(data.itemsByName.green_stained_glass_pane.id));const left=running.winner===uuid(alex.name);assert.equal(sam.window.items[0].itemId,data.itemsByName[left?'green_stained_glass_pane':'red_stained_glass_pane'].id);assert.equal(sam.window.items[6].itemId,data.itemsByName[left?'red_stained_glass_pane':'green_stained_glass_pane'].id);assert.equal(query("SELECT COUNT(*) AS n FROM ledger WHERE detail=? AND kind='FLIP_WIN'",'Coin flip #'+running.id)[0].n,1);await screenshotData('coinflip-result',sam);pass('Red/green animation ends with matching winner/loser frames, exact pot payout and one win receipt; closing/reopening cannot reroll');
 assert(alex.sounds>0&&sam.sounds>0);await click(sam,22);await wait(()=>sam.window?.title.includes('MK COIN FLIPS'),'back to lobby');pass('Completed match provides a Back to lobby button and enabled sounds reach both players');
 const heldBefore=balance(alex);await message(alex,'coinflip create 10','Created coin flip #');await wait(()=>balance(alex)===heldBefore,'expiry refund',16000);pass('Expired public wagers refund held money automatically');
 await message(alex,'coinflip create 10','Created coin flip #');alex.client.end();await wait(()=>balance(alex)===heldBefore,'host disconnect refund');alex=await connect('MarketAlex');assert.equal(balance(alex),heldBefore);pass('Waiting host disconnect refunds the wager without another starter grant');
 const disconnectedBefore=balance(alex)+balance(sam);await message(alex,'coinflip create 10','Created coin flip #');await open(sam,'coinflip','MK COIN FLIPS');await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM COIN FLIP'),'disconnect join');await click(sam,11);const disconnected=query("SELECT * FROM flips WHERE state='RUNNING'")[0];sam.client.end();await sleep(400);assert.equal(balance(alex)+balance(sam),disconnectedBefore-2000);await wait(()=>query('SELECT state FROM flips WHERE id=?',disconnected.id)[0].state==='DONE','offline payout');sam=await connect('MarketSam');assert.equal(balance(alex)+balance(sam),disconnectedBefore);pass('Disconnecting during an animation preserves the winner and pays normally, including offline wallets');
 config=config.replace('sound-enabled: true','sound-enabled: false');fs.writeFileSync(cfg,config);cmd('mksb reload');await sleep(500);const silentBefore=alex.sounds+sam.sounds;
 await message(alex,'coinflip create 1','Created coin flip #');await open(sam,'coinflip','MK COIN FLIPS');await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM COIN FLIP'),'muted join');await click(sam,11);const muted=query("SELECT * FROM flips WHERE state='RUNNING'")[0];await wait(()=>sam.messages.some(m=>m.includes(`in coin flip #${muted.id}!`)),'muted result');assert.equal(alex.sounds+sam.sounds,silentBefore);pass('Reloaded sound-disabled setting mutes ticking and result sounds without changing payout');
 cmd('op MarketAlex');await sleep(350);await message(alex,'mkmarket leaderboard place','leaderboard placed');await wait(()=>query('SELECT COUNT(*) AS n FROM board')[0].n===1,'board saved');await sleep(400);
 cmd('execute if entity @e[type=minecraft:text_display] run say BOARD_VISIBLE');await wait(()=>log.includes('BOARD_VISIBLE'),'visible leaderboard');pass('Admin can place a persistent in-world text leaderboard at spawn');
 await wait(()=>alex.messages.some(m=>m.includes('/auction')&&(m.includes('Open the coin flip lobby: /coinflip')||m.includes('Create a public wager: /coinflip'))),'public market reminder',35000);pass('Configurable chat reminders advertise auction and public coin flips');
 config=config.replace('enabled: true\n  interval-seconds: 30','enabled: false\n  interval-seconds: 30');fs.writeFileSync(cfg,config);cmd('mksb reload');await sleep(300);
 const timingOffset=log.length;cmd('mkmarket performance');await wait(()=>log.slice(timingOffset).includes('MK market work:'),'inventory transfer timings');samples.push({label:'market-timing-with-inventory-saves',text:log.slice(timingOffset).match(/MK market work:.*/)?.[0]});
 const bankBefore=[balance(alex),balance(sam),balance(lee)],mailBefore=query("SELECT COUNT(*) AS n FROM mail WHERE state='READY'")[0].n;
 // Capture real serialized inventory journals, then inject the two crash stages into the stopped fixture only.
 sql.exec("CREATE TABLE fixture_ops AS SELECT * FROM inventory_ops WHERE 0; CREATE TRIGGER fixture_capture AFTER INSERT ON inventory_ops BEGIN INSERT INTO fixture_ops SELECT * FROM inventory_ops WHERE id=NEW.id; END;");
 const beforeStage=await sell(alex,'gold_ingot',8,30),afterStage=await sell(lee,'copper_ingot',8,30);cmd('item replace entity MarketAlex hotbar.0 with minecraft:gold_ingot 8');await sleep(350);
 await message(alex,'coinflip create 1','Created coin flip #');await open(sam,'coinflip','MK COIN FLIPS');await click(sam,0);await wait(()=>sam.window?.title.includes('CONFIRM COIN FLIP'),'shutdown join');await click(sam,11);const shutdownFlip=query("SELECT * FROM flips WHERE state='RUNNING'")[0];assert(shutdownFlip);bankBefore[0]+=shutdownFlip.winner===uuid(alex.name)?100:-100;bankBefore[1]+=shutdownFlip.winner===uuid(sam.name)?100:-100;await stop();
 const inspect=new DatabaseSync(database);inspect.exec('DROP TRIGGER fixture_capture');for(const row of [beforeStage,afterStage]){inspect.prepare("UPDATE listings SET state='PENDING' WHERE id=?").run(row.id);inspect.prepare('INSERT INTO inventory_ops SELECT * FROM fixture_ops WHERE kind=\'LIST\' AND ref=?').run(row.id);}assert.equal(inspect.prepare('SELECT COUNT(*) AS n FROM inventory_ops').get().n,2);inspect.close();
 // Upgrade a real v1.5 configuration on Paper; retain custom timeout/mute and replace only shipped reminders.
 const legacy=fs.readFileSync(path.join(repo,'src/main/resources/config-v7.yml'),'utf8').replace('challenge-seconds: 60','challenge-seconds: 11\n  sound-enabled: false');fs.writeFileSync(cfg,legacy);
 await boot();config=fs.readFileSync(cfg,'utf8');assert(config.includes('config-version: 8')&&config.includes('waiting-seconds: 11')&&config.includes('sound-enabled: false')&&config.includes('animation-seconds: 5'));assert(config.includes('Open the coin flip lobby:')&&!config.includes('/coinflip Alex 50'));assert(fs.readdirSync(path.dirname(cfg)).some(name=>name.startsWith('config-before-v1.6.0-')));pass('Paper upgrades v1.5 config with a backup, preserves custom expiry/mute, and adds lobby defaults');
 alex=await connect('MarketAlex');sam=await connect('MarketSam');lee=await connect('MarketLee');await wait(()=>query('SELECT COUNT(*) AS n FROM inventory_ops')[0].n===0,'interrupted escrow reconciled');assert.deepEqual([balance(alex),balance(sam),balance(lee)],bankBefore);assert.equal(query("SELECT COUNT(*) AS n FROM mail WHERE state='READY'")[0].n,mailBefore);assert.equal(query('SELECT state FROM listings WHERE id=?',beforeStage.id)[0].state,'CANCELLED');assert.equal(query('SELECT state FROM listings WHERE id=?',afterStage.id)[0].state,'ACTIVE');
 assert.equal(query('SELECT state FROM flips WHERE id=?',shutdownFlip.id)[0].state,'DONE');assert.equal(query("SELECT COUNT(*) AS n FROM ledger WHERE detail=? AND kind='FLIP_WIN'",'Coin flip #'+shutdownFlip.id)[0].n,1);pass('Shutdown during an animation completes the saved winner once and restart preserves both balances');
 cmd('execute if items entity MarketAlex hotbar.0 minecraft:gold_ingot run say JOURNAL_ITEM_PRESERVED');await wait(()=>log.includes('JOURNAL_ITEM_PRESERVED'),'interrupted original item preserved');pass('Recovery reconciles real inventory snapshots before and after removal without replaying an item transfer');
 await sleep(11000);cmd('execute if entity @e[type=minecraft:text_display] run say BOARD_RESTORED');await wait(()=>log.includes('BOARD_RESTORED'),'board restored');pass('Wallets, offline mail and spawn leaderboard persist across full restart without duplicate $500 grants');
 await message(alex,'mkmarket leaderboard remove','leaderboard removed');cmd('execute unless entity @e[type=minecraft:text_display] run say BOARD_REMOVED');await wait(()=>log.includes('BOARD_REMOVED'),'board removed');assert.equal(query('SELECT COUNT(*) AS n FROM board')[0].n,0);pass('Admin removal deletes the in-world board and saved location');
 const offset=log.length;cmd('mkmarket performance');await wait(()=>log.slice(offset).includes('MK market work:'),'market timing');samples.push({label:'market-main-thread-timing',text:log.slice(offset).match(/MK market work:.*/)?.[0]});
 assert(!log.includes('Market transaction error')&&!log.includes('Coin flip transaction error')&&!log.includes('Coin flip menu error'));await stop();assert(!log.includes("Couldn't look up profile properties"));const report={version,result:'PASS',paper:'1.21.11 build 132',results,observations:samples,fixture:dir};fs.writeFileSync(path.join(dir,'market-report.json'),JSON.stringify(report,null,2));if(process.env.MK_MARKET_REPORT)fs.writeFileSync(process.env.MK_MARKET_REPORT,JSON.stringify(report,null,2));console.log('MARKET CHECKS PASSED:',results.length);
}catch(e){console.error(e.stack);fs.writeFileSync(path.join(dir,'failure.log'),log);process.exitCode=1;try{await stop();}catch{child?.kill();}}})();
